# spring.profiles.active: dev, prod

# yml syntax
spring:
    profiles:
        active:
          -  dev
          -  prod
guru:
    username: YmlUserName
    password: YmlPassword
    jdbcurl: YmlUrl

---
spring:
    profiles: prod
guru:
    username: YmlProdUserName
    password: YmlProdPassword
    jdbcurl: YmlProdUrl